### ISSUE TITLE
I'm getting an error when running "npm start"

### ISSUE THREAD

**Issue by paulwehner** [ShMcK/WebpackAngularDemos#4]
When running "npm start" for the Part1 project I get the following error and npm-debug.log. Do you know what the problem is?

> WebpackAngular@0.1.0 start /Users/.../WebpackAngularDemos-master/Part1
> node node_modules/.bin/webpack-dev-server --content-base app --hot
> 
> http://localhost:8080/webpack-dev-server/
> webpack result is served from /
> content is served from /Users/.../WebpackAngularDemos-master/Part1/app
> /Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/node/NodeWatchFileSystem.js:29
>       throw new Error("Invalid arguments: 'delay'");
>               ^
> Error: Invalid arguments: 'delay'
>    at NodeWatchFileSystem.watch (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/node/NodeWatchFileSystem.js:29:9)
>    at Watching.watch (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:86:47)
>    at Watching._done (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:82:8)
>    at Watching.<anonymous> (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:60:18)
>    at Tapable.emitRecords (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:279:37)
>    at Watching.<anonymous> (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:57:19)
>    at /Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:272:11
>    at Tapable.applyPluginsAsync (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
>    at Tapable.afterEmit (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:269:8)
>    at Tapable.<anonymous> (/Users/.../WebpackAngularDemos-master/Part1/node_modules/webpack/lib/Compiler.js:264:14)
> 
> npm ERR! Darwin 14.4.0
> npm ERR! argv "node" "/usr/local/bin/npm" "start"
> npm ERR! node v0.12.1
> npm ERR! npm  v2.7.5
> npm ERR! code ELIFECYCLE
> npm ERR! WebpackAngular@0.1.0 start: `node node_modules/.bin/webpack-dev-server --content-base app --hot`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the WebpackAngular@0.1.0 start script 'node node_modules/.bin/webpack-dev-server --content-base app --hot'.
> npm ERR! This is most likely a problem with the WebpackAngular package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node node_modules/.bin/webpack-dev-server --content-base app --hot
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls WebpackAngular
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/.../WebpackAngularDemos-master/Part1/npm-debug.log

Here is the npm-debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
> 2 info using npm@2.7.5
> 3 info using node@v0.12.1
> 4 verbose node symlink /usr/local/bin/node
> 5 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 6 info prestart WebpackAngular@0.1.0
> 7 info start WebpackAngular@0.1.0
> 8 verbose unsafe-perm in lifecycle true
> 9 info WebpackAngular@0.1.0 Failed to exec start script
> 10 verbose stack Error: WebpackAngular@0.1.0 start: `node node_modules/.bin/webpack-dev-server --content-base app --hot`
> 10 verbose stack Exit status 1
> 10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
> 10 verbose stack     at EventEmitter.emit (events.js:110:17)
> 10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
> 10 verbose stack     at ChildProcess.emit (events.js:110:17)
> 10 verbose stack     at maybeClose (child_process.js:1008:16)
> 10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
> 11 verbose pkgid WebpackAngular@0.1.0
> 12 verbose cwd /Users/.../WebpackAngularDemos-master/Part1
> 13 error Darwin 14.4.0
> 14 error argv "node" "/usr/local/bin/npm" "start"
> 15 error node v0.12.1
> 16 error npm  v2.7.5
> 17 error code ELIFECYCLE
> 18 error WebpackAngular@0.1.0 start: `node node_modules/.bin/webpack-dev-server --content-base app --hot`
> 18 error Exit status 1
> 19 error Failed at the WebpackAngular@0.1.0 start script 'node node_modules/.bin/webpack-dev->server --content-base app --hot'.
> 19 error This is most likely a problem with the WebpackAngular package,
> 19 error not with npm itself.
> 19 error Tell the author that this fails on your system:
> 19 error     node node_modules/.bin/webpack-dev-server --content-base app --hot
> 19 error You can get their info via:
> 19 error     npm owner ls WebpackAngular
> 19 error There is likely additional logging output above.
> 20 verbose exit [ 1, true ]

**Comment by ShMcK** [comment]
Quick question: Are you using Windows?

**Comment by ShMcK** [comment]
Make sure that this path: `node_modules/.bin/webpack-dev-server` is true. 

On Windows the path may be different as Windows uses back-slashes (`\`) as opposed to forward slashes (`/`).

**Comment by paulwehner** [comment]
Using Mac

**Comment by paulwehner** [comment]
If I check that path relative to the Part1 project folder, the path appears to be valid. There is a file called webpack-dev-server within node_module/.bin/

**Comment by ShMcK** [comment]
I found [a similar error](https://gitter.im/webpack/webpack/archives/2015/07/02) on the webpack Gitter discussion. The solution appeared to be updating the packages. `npm update webpack webpack-dev-server`, and possibly other packages. The [`npm-check-updates`](https://github.com/tjunnone/npm-check-updates) package can be a useful quick fix.

**Comment by schoeffman** [comment]
I was able to run Part 1 with no issue on a Mac (OSX 10.10.4) using webpack/webpack-dev-server version 2.10.1 . 

I too would think it is due to an older global module from being installed, and not project specific.

**Comment by ShMcK** [comment]
I updated the package a few days ago, have you tried it since? Actually, when I git cloned the repo and ran it I found it had the same error you had described, but it should be working now.

**Comment by paulwehner** [comment]
I just tried it and I can now run "npm start" and get the dev server to work. Thanks.

**Comment by ShMcK** [comment]
Great!
